### ISSUE TITLE
Make `methodName` in `codegen.js` customizable

### ISSUE THREAD

**Issue by pulkitsinghal** [wcandillon/swagger-js-codegen#34]
I want to submit a PR in order to make the following line of code in `codegen.js` configurable: 
`methodName: op.nickname,`
but I don't understand the library very well so I wanted to pick your brain first.

I want to do something like:
`methodName: (opts['nickname']) ? opts['nickname'](op) : op.nickname,`
so that by default if someone didn't want to customize the `methodName`, everything will remain backward compatible and just work. But if folks did want to change it then passing in a method to perform such a transformation would be how they accomplish this.

In the pseudo-code I wrote above, can you confirm if `opts` is the correct argument via which an action like passing in a custom function to this library would/should be performed?

**Comment by pulkitsinghal** [comment]
Also let me explain the motivation behind why I want to perform such a transformation. In the swagger spec generated by a 3rd party library, I receive nicknames like:
 - `normalMethodName`
 - `prototype.normalMethodName`
 - `prototype.__normalMethodName__className`

And I need to convert them to method names like the following for my nodejs client to work:
 - `normalMethodName`
 - `constructor.prototype.normalMethodName` or `constructor.normalMethodName`
 - `constructor.prototype.className.normalMethodName` or `constructor.className.normalMethodName`

So if a transformation method could be injected into `codegen.js` then it would be quite helpful for me.

**Comment by wcandillon** [comment]
@pulkitsinghal that make sense, you can go ahead with the PR.

**Comment by borisirota** [comment]
@wcandillon @pulkitsinghal 

swagger supports [vendor extensions](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#specification-extensions-).  
What do you think about adding special property to support custom method names (something like `x-swagger-js-codegen-method-name`)?

Example:
```
  /users:
    x-swagger-router-controller: usersCtrl
    post:
      summary: Add user
      description: Add user
      operationId: add
      x-swagger-js-codegen-method-name: userAdd
      parameters:
        -
          name: user
          in: body
          description: user's object
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: New user created
          headers:
            Location: 
              description: New user id
              type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
```

**Comment by wcandillon** [comment]
@borisirota Why do you believe it should be different from operationId?

**Comment by borisirota** [comment]
I see. My use case:

I'm using swagger-tools and swaggerRouter which maps the operationId into a method inside a specific controller (specified in x-swagger-router-controller).  

There is one swagger file containing all the api paths -> the API composed of several models -> each model implemented in its own controller (it doesn't have to be this way, but its a modular and a convenient separation) -> simple CRUD operations are being called add, remove, findById, etc. in every controller -> several controllers contains same operations names (I can suffix\prefix user for every operation in the users controller for example but it seems redundant and not clean) -> the generated code has duplicated method names because what is being generated is one model containing all the original models together and not file per every model.

My main conflict is that I already use the swagger file in order to make automatic routing on the server side and it uses other conventions than this module (this code generator see it as one model and swagger router see it as composition of separate models).

The current solution for me is to make sure there is no method names duplications between all the controllers (in usersCtrl I'll call userAdd, userRemove, etc.) but it seems to be not the right approach.

The appropriate solution for me will be as I proposed (which actually is updating one line of code).

I agree with you about the specific use cases in general, but I really think that because the generator generates one big model (based on one swagger file) containing of several models which can be implemented separately, it should address this issue and add this simple support as an option :)

Do you still think that this is a specific use case that shouldn't be supported by the generator ?

Thanks!

**Comment by borisirota** [comment]
Thanks ! :)
